import os
from pathlib import Path
from dotenv import load_dotenv
import pymysql
import json
import requests

from slack_sdk import WebClient
from flask import Flask, request
from slackeventsapi import SlackEventAdapter
from slack_sdk.errors import SlackApiError
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from slack_bolt.adapter.flask import SlackRequestHandler


env_path = Path('..') / '.env'
load_dotenv(dotenv_path=env_path)
# Initializes your app with your bot token and socket mode handler
app = App(
    token=os.environ.get("CAT_BOT_TOKEN"),
    # signing_secret=os.environ.get("SLACK_SIGNING_SECRET") # not required for socket mode
)

# Initialize Flask app
flask_app = Flask(__name__)

# SlackRequestHandler translates WSGI requests to Bolt's interface
# and builds WSGI response from Bolt's response.
handler = SlackRequestHandler(app)

# Register routes to Flask app
@flask_app.route("/slack/events", methods=["POST"])
def slack_events():
    # handler runs App's dispatch method
    return handler.handle(request)

slack_event_adapter = SlackEventAdapter(os.environ['CAT_BOT_SIGNING_SECRET'], '/slack/events', flask_app)

# Define the client obj
client = WebClient(token=os.environ['CAT_BOT_TOKEN'])
# Get the bot id
BOT_ID = client.api_call("auth.test")['user_id']

def getAllUsersInfo():
    '''
    Helper function to get all users info from slack
    Takes a users array we get from slack which is a SlackResponse object type
    Returns a dict type containing same info with user id as key
    '''
    # Call the users.list method using the WebClient
    # users.list requires the users:read scope
    result = client.users_list()
    # Get all user info in result
    users_array = result["members"]
    users_store = {}
    # turn the SlackResponse object type into dict type
    for user in users_array:
        # Key user info on their unique user ID
        user_id = user["id"]
        # Store the entire user object (you may not need all of the info)
        users_store[user_id] = user
    return users_store

def generateMessage(assignList):
    '''
    Helper function for sendTasks.
    Get the list of task assigned to a user and format them into a 
    json block message.
    Return the block message
    '''
    block = []
    for taskInfo in assignList:
        text = ("Task" + str(taskInfo[0]) + " Location: " + taskInfo[2] + 
                "\nDescription: " + taskInfo[3] + 
                "\nStart time: " + str(taskInfo[4]) + " Window: " + str(taskInfo[5])+ 
                "\nCompensation: " + str(taskInfo[6]))
        block.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": text
                }
            }
        )
        block.append(
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "Accept",
                        },
                        "value": "accept"
                    },
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "Reject",
                        },
                        "value": "reject"
                    }
                ],
                "block_id": str(taskInfo[0])
            }
        )
    return block

def sendTasks(assignmentsDict):
    '''
    * Message users to give them new tasks *
    Takes the assignments dictionary generated by getAssignments() in messenger
    Format the tasks each user get into block messages. Send them to each 
        user respectively
    Returns nothing
    ''' 
    for user_id in assignmentsDict:
        if BOT_ID != user_id:    
            try:
                reply = generateMessage(assignmentsDict[user_id])
                texts = "Here are your newly generated tasks"
                client.chat_postMessage(channel=f"@{user_id}", text = texts, blocks = reply)
            except SlackApiError as e:
                # You will get a SlackApiError if "ok" is False
                assert e.response["ok"] is False
                # str like 'invalid_auth', 'channel_not_found'
                assert e.response["error"]
                print(f"Got an error: {e.response['error']}")
'''
# Listens to incoming messages that contain "hello"
@app.message("hello")
def message_hello(message, say):
    # say() sends a message to the channel where the event was triggered
    say(
        blocks=[
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"Hey there <@{message['user']}>!"},
                "accessory": {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Click Me"},
                    "action_id": "button_click"
                }
            }
        ],
        text=f"Hey there <@{message['user']}>!"
    )
'''

@app.message()
def any_message(payload, say):
    """
    Takes the response from a message sent in any chat in which this Bot has
        access to.
    When on, constantly listens for new messages, the responds as dictated below.
    Returns nothing.
    """
    # Recieve payload
    print(payload)
    channel_id = payload.get('channel')
    user_id = payload.get('user')
    text = payload.get('text')
    #print(f'\nUSER_ID: {user_id}\n')
    
    # Handle certain responses
    if BOT_ID != user_id:
        if text == "hi":
            try:
                reply = [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": text
                        }
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "Accept",
                                },
                                "value": "accept",
                                "action_id" : "accept"
                            },
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "Reject",
                                },
                                "value": "reject",
                                "action_id" : "reject"
                            }
                        ],
                        "block_id": "task1"
                    }
                ]
                say(blocks = reply, text = "new tasks")
                #client.chat_postMessage(channel=f"@{user_id}", blocks = reply)
            except SlackApiError as e:
                # You will get a SlackApiError if "ok" is False
                assert e.response["ok"] is False
                # str like 'invalid_auth', 'channel_not_found'
                assert e.response["error"]
                print(f"Got an error: {e.response['error']}")

        else:
            try:
                reply = [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": text
                        }
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "Accept",
                                },
                                "value": "accept",
                                "action_id" : "accept"
                            },
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "Reject",
                                },
                                "value": "reject",
                                "action_id" : "reject"
                            }
                        ],
                        "block_id": "task2"
                    }
                ]
                say(blocks = reply, text = "new tasks")
                #client.chat_postMessage(channel=f"@{user_id}", blocks = reply)
            except SlackApiError as e:
                # You will get a SlackApiError if "ok" is False
                assert e.response["ok"] is False
                # str like 'invalid_auth', 'channel_not_found'
                assert e.response["error"]
                print(f"Got an error: {e.response['error']}")

def getPic(url, token, user_id, task_id):
    '''
    Takes   url: from payload['event']['files'][0]['url_private_download']
            token: the bot token
            user_id: the user who sent the picture
            task_id: the task they are trying to finish, should be payload['event']['text']
    Downloads picture with the given download url and saves it in the given path
    '''
    r = requests.get(url, headers={'Authorization': 'Bearer %s' % token})
    dateTime = 0 # switch to clock
    filename = f"../../snapngo_pics/{user_id}_{task_id}_{dateTime}.jpeg"
    open(filename, 'wb').write(r.content)


@app.action("accept")
def action_button_click(body, ack, say):
    '''
    body['actions'][0]   {'value': 'accept', 'block_id': 'task1', 'type': 'button', 'action_id': 'accept', 'text':...}
    '''
    # Acknowledge the action
    ack()
    print("ACCEPT")
    print(body)
    #say(f"<@{body['user']['id']}> clicked the button")

@app.action("reject")
def action_button_click(body, ack, say):
    # Acknowledge the action
    ack()
    print("REJECT")
    print(body)
    #say(f"<@{body['user']['id']}> clicked the button")

# Start your app
if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()